<?php

namespace ReuniounouBundle\Repository;


/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByEmail($email)
    {
        $qb = $this->_em->createQueryBuilder('u');

        $qb ->select('u.password')
            ->from('ReuniounouBundle:Utilisateur', 'u')
            ->where('u.email = :email')
            //->andWhere('u.motDePasse = :motDePasse')
            ->setParameter('email', $email);
            //->setParameter('motDePasse', $motDePasse);

        $requete = $qb->getQuery();

        try
        {
            $result = $requete->getSingleResult();
        }
        catch (\Doctrine\ORM\NoResultException $e)
        {
            $result = "NoResultException";
        }

        return $result;
    }
}
